const LOAD_COMMENTS = 'LOAD_COMMENTS';
const LOAD_POSTS = 'LOAD_POSTS';
const LOAD_SINGLE_USER = 'LOAD_SINGLE_USER';
const LOAD_USERS = 'LOAD_USERS';

export {
    LOAD_COMMENTS,
    LOAD_POSTS,
    LOAD_SINGLE_USER,
    LOAD_USERS
}